CREATE TABLE WZW_BONUS(
ID VARCHAR(32) NOT NULL,
EMPLOYE_NAME VARCHAR(100) NOT NULL,
WZW_WAGE DOUBLE(20,2) NOT NULL,
WZW_BOUNS DOUBLE(20,2) NOT NULL,
REAL_TOTAL_BONUS DOUBLE(20,2),
OPT_YEAR_BONUS DOUBLE(20,2),
OPT_MONTH1_BONUS DOUBLE(20,2),
OPT2_MONTH2_BONUS DOUBLE(20,2),
TAX DOUBLE(20,2),
PRIMARY KEY (ID)
);
